[config]
version_check = false

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/default/matugen-colors.lua'
post_hook = "hyprctl reload"

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock/matugen-colors.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar/matugen-colors.css'
post_hook = "systemctl --user restart waybar"

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/matugen-colors.css'

# [templates.gtk3]
# input_path = '~/.config/matugen/templates/gtk-3.0/gtk.css'
# output_path = '~/.config/gtk-3.0/gtk.css'
#
# [templates.gtk4]
# input_path = '~/.config/matugen/templates/gtk-4.0/gtk.css'
# output_path = '~/.config/gtk-4.0/gtk.css'
#
# [templates.kde_colors]
# input_path = '~/.config/matugen/templates/kde/color.txt'
# output_path = '~/.local/state/quickshell/user/generated/color.txt'
#
# [templates.wallpaper]
# input_path = '~/.config/matugen/templates/wallpaper.txt'
# output_path = '~/.local/state/quickshell/user/generated/wallpaper/path.txt'
