[config]
version_check = false

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/matugen/generated/hyprland-colors.lua'
post_hook = "hyprctl reload"

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.config/matugen/generated/hyprlock-colors.conf'

[templates.css]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/matugen/generated/colors.css'
post_hook = "systemctl --user restart waybar"

# [templates.hyprlock]
# input_path = '~/.config/matugen/templates/hyprland/hyprlock-colors.conf'
# output_path = '~/.config/hypr/hyprlock/colors.conf'
#
# [templates.gtk3]
# input_path = '~/.config/matugen/templates/gtk-3.0/gtk.css'
# output_path = '~/.config/gtk-3.0/gtk.css'
#
# [templates.gtk4]
# input_path = '~/.config/matugen/templates/gtk-4.0/gtk.css'
# output_path = '~/.config/gtk-4.0/gtk.css'
#
# [templates.kde_colors]
# input_path = '~/.config/matugen/templates/kde/color.txt'
# output_path = '~/.local/state/quickshell/user/generated/color.txt'
#
# [templates.wallpaper]
# input_path = '~/.config/matugen/templates/wallpaper.txt'
# output_path = '~/.local/state/quickshell/user/generated/wallpaper/path.txt'
